SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- 如果本脚本用于 Docker 初始化目录 /container-entrypoint-initdb.d，保留 CONNECT。
-- 如果你已经用 CAMPUS 用户登录 SQL*Plus 后手动执行，也可以删除下一行。
CONNECT CAMPUS/Campus123456@//localhost:1521/FREEPDB1

/*
  校园二手交易系统 Oracle 建表脚本
  说明：
  1. 原设计文档中的 user 表在 Oracle 中改名为 app_user，避免与 Oracle USER 关键字/函数冲突。
  2. 原设计文档中的 goods.condition 字段改名为 goods_condition，避免字段名歧义。
  3. MySQL 类型已转换为 Oracle 类型：
     INT -> NUMBER(11)
     VARCHAR -> VARCHAR2
     TEXT -> CLOB
     DATETIME -> TIMESTAMP
     DECIMAL(10,2) -> NUMBER(10,2)
     TINYINT -> NUMBER
     AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
  4. MySQL 的 ON UPDATE 自动更新时间改为 Oracle 触发器实现。
*/

/* =========================
   1. 用户与身份模块
   ========================= */

CREATE TABLE app_user (
    user_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(64) NOT NULL,
    nickname VARCHAR2(50) DEFAULT '新用户',
    avatar VARCHAR2(255),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    role VARCHAR2(20) DEFAULT 'buyer' NOT NULL,
    status VARCHAR2(20) DEFAULT 'normal' NOT NULL,
    credit_score NUMBER(11) DEFAULT 100 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_role CHECK (role IN ('buyer', 'seller', 'admin')),
    CONSTRAINT ck_app_user_status CHECK (status IN ('normal', 'banned')),
    CONSTRAINT ck_app_user_credit_score CHECK (credit_score >= 0)
);

CREATE TABLE student_auth (
    auth_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(11) NOT NULL,
    student_id VARCHAR2(30) NOT NULL,
    real_name VARCHAR2(50) NOT NULL,
    college VARCHAR2(100) NOT NULL,
    auth_status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    auth_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_student_auth PRIMARY KEY (auth_id),
    CONSTRAINT uq_student_auth_user_id UNIQUE (user_id),
    CONSTRAINT fk_student_auth_user FOREIGN KEY (user_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_student_auth_status CHECK (auth_status IN ('pending', 'approved', 'rejected'))
);

/* =========================
   2. 商品管理模块
   ========================= */

CREATE TABLE category (
    category_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(50) NOT NULL,
    parent_id NUMBER(11),
    sort_order NUMBER(11) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id)
        REFERENCES category(category_id),
    CONSTRAINT ck_category_not_self CHECK (parent_id IS NULL OR parent_id <> category_id)
);

CREATE TABLE goods (
    goods_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    seller_id NUMBER(11) NOT NULL,
    category_id NUMBER(11) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    goods_condition VARCHAR2(20) NOT NULL,
    goods_status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    view_count NUMBER(11) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT pk_goods PRIMARY KEY (goods_id),
    CONSTRAINT fk_goods_seller FOREIGN KEY (seller_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_goods_category FOREIGN KEY (category_id)
        REFERENCES category(category_id),
    CONSTRAINT ck_goods_price CHECK (price >= 0),
    CONSTRAINT ck_goods_condition CHECK (goods_condition IN ('全新', '几乎全新', '轻微使用', '明显痕迹')),
    CONSTRAINT ck_goods_status CHECK (goods_status IN ('pending', 'approved', 'rejected', 'locked', 'sold', 'offline')),
    CONSTRAINT ck_goods_view_count CHECK (view_count >= 0)
);

CREATE TABLE goods_image (
    image_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    goods_id NUMBER(11) NOT NULL,
    image_url VARCHAR2(255) NOT NULL,
    sort_order NUMBER(11) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_goods_image PRIMARY KEY (image_id),
    CONSTRAINT fk_goods_image_goods FOREIGN KEY (goods_id)
        REFERENCES goods(goods_id)
);

CREATE TABLE favorite (
    favorite_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(11) NOT NULL,
    goods_id NUMBER(11) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_favorite PRIMARY KEY (favorite_id),
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_favorite_goods FOREIGN KEY (goods_id)
        REFERENCES goods(goods_id),
    CONSTRAINT uq_favorite_user_goods UNIQUE (user_id, goods_id)
);

/* =========================
   3. 议价与交易模块
   ========================= */

CREATE TABLE bargain_offer (
    offer_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    goods_id NUMBER(11) NOT NULL,
    buyer_id NUMBER(11) NOT NULL,
    offer_price NUMBER(10, 2) NOT NULL,
    seller_response VARCHAR2(20) DEFAULT 'pending',
    counter_price NUMBER(10, 2),
    offer_status VARCHAR2(20) DEFAULT 'active' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT pk_bargain_offer PRIMARY KEY (offer_id),
    CONSTRAINT fk_bargain_offer_goods FOREIGN KEY (goods_id)
        REFERENCES goods(goods_id),
    CONSTRAINT fk_bargain_offer_buyer FOREIGN KEY (buyer_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_bargain_offer_price CHECK (offer_price >= 0),
    CONSTRAINT ck_bargain_counter_price CHECK (counter_price IS NULL OR counter_price >= 0),
    CONSTRAINT ck_bargain_seller_response CHECK (seller_response IN ('pending', 'accepted', 'rejected', 'countered')),
    CONSTRAINT ck_bargain_offer_status CHECK (offer_status IN ('active', 'accepted', 'rejected', 'closed')),
    CONSTRAINT ck_bargain_counter_required CHECK (
        (seller_response = 'countered' AND counter_price IS NOT NULL)
        OR
        (seller_response <> 'countered')
    )
);

CREATE TABLE trade_order (
    order_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    goods_id NUMBER(11) NOT NULL,
    buyer_id NUMBER(11) NOT NULL,
    seller_id NUMBER(11) NOT NULL,
    final_price NUMBER(10, 2) NOT NULL,
    order_status VARCHAR2(20) DEFAULT 'pending_meet' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT pk_trade_order PRIMARY KEY (order_id),
    CONSTRAINT fk_trade_order_goods FOREIGN KEY (goods_id)
        REFERENCES goods(goods_id),
    CONSTRAINT fk_trade_order_buyer FOREIGN KEY (buyer_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_trade_order_seller FOREIGN KEY (seller_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_trade_order_price CHECK (final_price >= 0),
    CONSTRAINT ck_trade_order_status CHECK (order_status IN ('pending_meet', 'in_meet', 'completed', 'cancelled')),
    CONSTRAINT ck_trade_order_buyer_seller CHECK (buyer_id <> seller_id)
);

CREATE TABLE appointment (
    appointment_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(11) NOT NULL,
    meet_time TIMESTAMP NOT NULL,
    meet_place VARCHAR2(255) NOT NULL,
    confirm_code VARCHAR2(10) NOT NULL,
    appointment_status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_appointment PRIMARY KEY (appointment_id),
    CONSTRAINT uq_appointment_order_id UNIQUE (order_id),
    CONSTRAINT fk_appointment_order FOREIGN KEY (order_id)
        REFERENCES trade_order(order_id),
    CONSTRAINT ck_appointment_status CHECK (appointment_status IN ('pending', 'confirmed', 'completed', 'cancelled')),
    CONSTRAINT ck_appointment_confirm_code_len CHECK (LENGTH(confirm_code) BETWEEN 6 AND 10)
);

/* =========================
   4. 沟通模块
   ========================= */

CREATE TABLE chat_session (
    session_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    goods_id NUMBER(11) NOT NULL,
    buyer_id NUMBER(11) NOT NULL,
    seller_id NUMBER(11) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_chat_session PRIMARY KEY (session_id),
    CONSTRAINT fk_chat_session_goods FOREIGN KEY (goods_id)
        REFERENCES goods(goods_id),
    CONSTRAINT fk_chat_session_buyer FOREIGN KEY (buyer_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_chat_session_seller FOREIGN KEY (seller_id)
        REFERENCES app_user(user_id),
    CONSTRAINT uq_chat_session_goods_buyer_seller UNIQUE (goods_id, buyer_id, seller_id),
    CONSTRAINT ck_chat_session_buyer_seller CHECK (buyer_id <> seller_id)
);

CREATE TABLE chat_message (
    message_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    session_id NUMBER(11) NOT NULL,
    sender_id NUMBER(11) NOT NULL,
    content CLOB NOT NULL,
    is_read NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_chat_message PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_message_session FOREIGN KEY (session_id)
        REFERENCES chat_session(session_id),
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_chat_message_is_read CHECK (is_read IN (0, 1))
);

/* =========================
   5. 评价与举报模块
   ========================= */

CREATE TABLE review (
    review_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(11) NOT NULL,
    reviewer_id NUMBER(11) NOT NULL,
    reviewed_user_id NUMBER(11) NOT NULL,
    rating NUMBER(1) NOT NULL,
    content CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_review PRIMARY KEY (review_id),
    CONSTRAINT fk_review_order FOREIGN KEY (order_id)
        REFERENCES trade_order(order_id),
    CONSTRAINT fk_review_reviewer FOREIGN KEY (reviewer_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_review_reviewed_user FOREIGN KEY (reviewed_user_id)
        REFERENCES app_user(user_id),
    CONSTRAINT uq_review_order_reviewer UNIQUE (order_id, reviewer_id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_users CHECK (reviewer_id <> reviewed_user_id)
);

CREATE TABLE report (
    report_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    reporter_id NUMBER(11) NOT NULL,
    report_type VARCHAR2(20) NOT NULL,
    target_goods_id NUMBER(11),
    target_user_id NUMBER(11),
    target_order_id NUMBER(11),
    reason CLOB NOT NULL,
    report_status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_report PRIMARY KEY (report_id),
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_report_target_goods FOREIGN KEY (target_goods_id)
        REFERENCES goods(goods_id),
    CONSTRAINT fk_report_target_user FOREIGN KEY (target_user_id)
        REFERENCES app_user(user_id),
    CONSTRAINT fk_report_target_order FOREIGN KEY (target_order_id)
        REFERENCES trade_order(order_id),
    CONSTRAINT ck_report_type CHECK (report_type IN ('goods', 'user', 'order')),
    CONSTRAINT ck_report_status CHECK (report_status IN ('pending', 'processing', 'resolved', 'rejected')),
    CONSTRAINT ck_report_target_by_type CHECK (
        (report_type = 'goods' AND target_goods_id IS NOT NULL AND target_user_id IS NULL AND target_order_id IS NULL)
        OR
        (report_type = 'user' AND target_goods_id IS NULL AND target_user_id IS NOT NULL AND target_order_id IS NULL)
        OR
        (report_type = 'order' AND target_goods_id IS NULL AND target_user_id IS NULL AND target_order_id IS NOT NULL)
    )
);

/* =========================
   6. 后台管理模块
   ========================= */

CREATE TABLE audit_log (
    log_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    admin_id NUMBER(11) NOT NULL,
    audit_type VARCHAR2(30) NOT NULL,
    target_id NUMBER(11) NOT NULL,
    action VARCHAR2(50) NOT NULL,
    result VARCHAR2(100),
    remark CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_log PRIMARY KEY (log_id),
    CONSTRAINT fk_audit_log_admin FOREIGN KEY (admin_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_audit_log_type CHECK (audit_type IN ('goods_audit', 'report_handle', 'user_ban', 'goods_offline'))
);

CREATE TABLE notice (
    notice_id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    notice_type VARCHAR2(30) NOT NULL,
    publisher_id NUMBER(11) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT pk_notice PRIMARY KEY (notice_id),
    CONSTRAINT fk_notice_publisher FOREIGN KEY (publisher_id)
        REFERENCES app_user(user_id),
    CONSTRAINT ck_notice_type CHECK (notice_type IN ('system', 'transaction', 'violation'))
);

/* =========================
   7. 常用索引
   ========================= */

CREATE INDEX idx_student_auth_student_id ON student_auth(student_id);
CREATE INDEX idx_category_parent_id ON category(parent_id);
CREATE INDEX idx_goods_seller_id ON goods(seller_id);
CREATE INDEX idx_goods_category_id ON goods(category_id);
CREATE INDEX idx_goods_status ON goods(goods_status);
CREATE INDEX idx_goods_created_at ON goods(created_at);
CREATE INDEX idx_goods_image_goods_id ON goods_image(goods_id);
CREATE INDEX idx_favorite_user_id ON favorite(user_id);
CREATE INDEX idx_favorite_goods_id ON favorite(goods_id);
CREATE INDEX idx_bargain_offer_goods_id ON bargain_offer(goods_id);
CREATE INDEX idx_bargain_offer_buyer_id ON bargain_offer(buyer_id);
CREATE INDEX idx_trade_order_goods_id ON trade_order(goods_id);
CREATE INDEX idx_trade_order_buyer_id ON trade_order(buyer_id);
CREATE INDEX idx_trade_order_seller_id ON trade_order(seller_id);
CREATE INDEX idx_trade_order_status ON trade_order(order_status);
CREATE INDEX idx_chat_session_goods_id ON chat_session(goods_id);
CREATE INDEX idx_chat_session_buyer_id ON chat_session(buyer_id);
CREATE INDEX idx_chat_session_seller_id ON chat_session(seller_id);
CREATE INDEX idx_chat_message_session_id ON chat_message(session_id);
CREATE INDEX idx_chat_message_sender_id ON chat_message(sender_id);
CREATE INDEX idx_review_order_id ON review(order_id);
CREATE INDEX idx_review_reviewer_id ON review(reviewer_id);
CREATE INDEX idx_review_reviewed_user_id ON review(reviewed_user_id);
CREATE INDEX idx_report_reporter_id ON report(reporter_id);
CREATE INDEX idx_report_status ON report(report_status);
CREATE INDEX idx_audit_log_admin_id ON audit_log(admin_id);
CREATE INDEX idx_notice_publisher_id ON notice(publisher_id);

/* =========================
   8. updated_at 自动更新时间触发器
   ========================= */

CREATE OR REPLACE TRIGGER trg_app_user_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_goods_updated_at
BEFORE UPDATE ON goods
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_bargain_offer_updated_at
BEFORE UPDATE ON bargain_offer
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_trade_order_updated_at
BEFORE UPDATE ON trade_order
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_notice_updated_at
BEFORE UPDATE ON notice
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

/* =========================
   9. 表与字段说明
   ========================= */

COMMENT ON TABLE app_user IS '用户表：存储用户账号基础信息、角色、状态及信用分';
COMMENT ON TABLE student_auth IS '学生认证表：存储校园实名认证信息，与用户一对一关联';
COMMENT ON TABLE category IS '商品分类表：管理商品多级分类，支持父分类自关联';
COMMENT ON TABLE goods IS '商品表：存储商品核心信息，关联卖家与分类';
COMMENT ON TABLE goods_image IS '商品图片表：存储商品图片URL及排序';
COMMENT ON TABLE favorite IS '收藏表：记录用户与商品之间的收藏关系';
COMMENT ON TABLE bargain_offer IS '议价表：存储买家对商品的议价记录';
COMMENT ON TABLE trade_order IS '订单表：存储真实交易订单';
COMMENT ON TABLE appointment IS '面交预约表：存储线下面交预约信息及确认码';
COMMENT ON TABLE chat_session IS '会话表：记录买卖双方围绕某件商品建立的私聊会话';
COMMENT ON TABLE chat_message IS '消息表：存储会话中的聊天消息内容与已读状态';
COMMENT ON TABLE review IS '评价表：记录交易完成后的买卖双方互评';
COMMENT ON TABLE report IS '举报表：统一存储对商品、用户或订单的举报信息';
COMMENT ON TABLE audit_log IS '审核日志表：记录管理员后台审核与处理操作';
COMMENT ON TABLE notice IS '公告表：存储系统公告、交易须知、违规提醒等';

COMMIT;

EXIT;
